AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    Sample Application
    
Parameters:
  Func01Name:
    Type: String

Resources:
  LambdaFunction01:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: !Sub ${Func01Name}/
      #InlineCode:
      FunctionName: !Sub ${Func01Name}
      #Description: !Sub ${Func01Description}
      MemorySize: 128
      #Timeout: 60
      Role:
      #Policies:
      Environment: 
        Variables:
          LOGGING: INFO
      #VpcConfig:
      Events:
        API01:
          Type: Api
          Properties:
            Path: /getuser/{username}
            Method: get
        API02:
          Type: Api
          Properties:
            Path: /updateuser
            Method: put
      Tags:
        Owner: sample
        Environment: v1
      #Tracing:
      #KmsKeyArn:
      #DeadLetterQueue:
      #DeploymentPreference:
      #Layers:
      #AutoPublishAlias: v1
      #ReservedConcurrentExecutions: dev    