AWSTemplateFormatVersion: 2010-09-09
Description: |
  TEST
Parameters:
  vpcid:
    Description: "-"
    Type: AWS::EC2::VPC::Id

#Metadata:
  
#Mappings:
  
#Conditions:
  
Resources:
  # スポットインスタンス起動用テンプレート
  spotinsttemplate:
    Type: "AWS::EC2::LaunchTemplate"
    Properties:
      LaunchTemplateName: "spotinsttemplate"
      LaunchTemplateData:
        InstanceMarketOptions:
          SpotOptions:
            SpotInstanceType: "one-time"
            InstanceInterruptionBehavior: "terminate"
          MarketType: "spot"
        ImageId: "ami-068a6cefc24c301d2"
        InstanceType: "t3.micro"
        IamInstanceProfile: 
          Arn: !GetAtt  EC2IAMProfile.Arn
        SecurityGroupIds: 
          - !Ref ec2sg
        UserData:
          Fn::Base64: |
            #!/bin/bash
            timedatectl set-timezone 'Asia/Tokyo'
            systemctl start amazon-ssm-agent
            yum -y install httpd.x86_64
            systemctl start httpd

    # EC2 Iam role
  EC2IAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      AssumeRolePolicyDocument: {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Sid": "",
                    "Effect": "Allow",
                    "Principal": {
                        "Service": "ec2.amazonaws.com"
                    },
                    "Action": "sts:AssumeRole"
                }
            ]
        }
      Path: "/ec2/"
      MaxSessionDuration: 3600
      RoleName: !Sub TEST-Role

  EC2IAMProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/ec2/"
      Roles:
        - !Ref EC2IAMRole
      InstanceProfileName: TEST-Profile

  albsg:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "-"
      GroupName: !Sub TEST-ALBSG
      #SecurityGroupEgress:
      #  - Egress
      # とりあえずIPを指定しておく
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 219.101.159.1/32
          FromPort: 443
          ToPort: 443
        - IpProtocol: tcp
          CidrIp: 219.101.159.1/32
          FromPort: 80
          ToPort: 80
      #Tags:
      #  - Tag
      VpcId: !Ref vpcid

  ec2sg:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "-"
      GroupName: !Sub TEST-EC2SG
      #SecurityGroupEgress:
      #  - Egress
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref albsg
      #Tags:
      #  - Tag
      VpcId: !Ref vpcid

#Transform:
  
#Outputs: