AWSTemplateFormatVersion: 2010-09-09
Description: |
  
Parameters:
  PublicSubet1aID:
    Type: AWS::EC2::Subnet::Id
  PrivateRouteTable1a:
    Type: String
  ProjectName:
    Type: String
    Default: 'Project'

Resources:
  # --- for PublicSubnet 1a ---
  ForNatGatewayPublicSubnet1a:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: 'vpc'
      #Tags:
      #  - Key: Name
      #    Value: !Sub ${ProjectName}-ForNatGatewayPublicSubnet1a
  
  NatGatewayPublicSubnet1a:
    Type: "AWS::EC2::NatGateway"
    Properties:
      AllocationId: !GetAtt ForNatGatewayPublicSubnet1a.AllocationId
      SubnetId: !Ref PublicSubet1aID
      Tags:
        - Key: Name 
          Value: !Sub ${ProjectName}-NatGatewayPublicSubnet1a

  RouteTableAddPrivateSubnet1a:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGatewayPublicSubnet1a
      RouteTableId: !Ref PrivateRouteTable1a
